export const CHANGE_SEARCH_FILTER_FIELD = 'CHANGE_SEARCH_FILTER_FIELD';
export const CHANGE_DARK_MODE = 'CHANGE_DARK_MODE';
export const REQUEST_TASKS_PENDING = 'REQUEST_TASKS_PENDING';
export const REQUEST_TASKS_SUCCESS = 'REQUEST_TASKS_SUCCESS';
export const REQUEST_TASKS_FAIL = 'REQUEST_TASKS_FAIL';

