export const CHANGE_SEARCH_FILTER_FIELD = 'CHANGE_SEARCH_FILTER_FIELD';
export const CHANGE_DARK_MODE = 'CHANGE_DARK_MODE';
export const CHANGE_FONT_FAMILY = 'CHANGE_FONT_FAMILY';
export const CHANGE_WEATHER_LOCATION = 'CHANGE_WEATHER_LOCATION';
export const CHANGE_FONT_SIZE = 'CHANGE_FONT_SIZE';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const CHANGE_INBOX_REMINDER = 'CHANGE_INBOX_REMINDER';
export const CHANGE_NOTES_REMINDER = 'CHANGE_NOTES_REMINDER';
export const CHANGE_NAVBAR_REMINDER = 'CHANGE_NAVBAR_REMINDER';
export const CHANGE_TIME_ZONE = 'CHANGE_TIME_ZONE';
export const CHANGE_TIME_FORMAT = 'CHANGE_TIME_FORMAT';
export const CHANGE_WEATHER_FORMAT = 'CHANGE_WEATHER_FORMAT';

export const GET_TASKS_REQUEST = 'GET_TASKS_REQUEST';
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_TASKS_FAILURE = 'GET_TASKS_FAILURE';


