export const CHANGE_SEARCH_FILTER_FIELD = 'CHANGE_SEARCH_FILTER_FIELD';
export const CHANGE_DARK_MODE = 'CHANGE_DARK_MODE';
export const CHANGE_FONT_FAMILY = 'CHANGE_FONT_FAMILY';
export const CHANGE_WEATHER_LOCATION = 'CHANGE_WEATHER_LOCATION';


